### ISSUE TITLE
Unparseable METARs

### ISSUE THREAD

**Issue by aeshirey** [lilopkins/metar-rs#22]
I've come across some METARs that don't parse:

```text
KPVG 181956Z AUTO 10SM FEW030 SCT035 BKN050 A2982 RMK AO2 SLPNO FZRANO PNO $
KPVG 181855Z 10SM FEW025 OVC034 A2983 RMK AO2 PWINO PNO FZRANO RVRNO
KGWW 191150Z AUTO 00000KT 14/14 A3007 RMK AO2 70001 T01410140 10145 20122
CYWG 190500Z 16014KT 10SM SKC 19/11 A2959 RMK SLP022 DENSITY ALT 1800FT
CYWG 190400Z 15011KT 9SM SKC 18/12 A2960 RMK SLP027 DENSITY ALT 1700FT
KFCI 200356Z AUTO 00000KT SCT070 15/15 RMK AO2 SLPNO T01500150 402610111 PWINO $
KFCI 200256Z AUTO 00000KT BKN070 16/16 RMK AO2 SLPNO T01610156 PWINO $
KPHF 191054Z 00000KT 5SM BR CLR 11/11 A3003 RMK AO2 SLP168 T01110111
MDSD 192000Z 08008KT 9999 FEW020CB FEW022 BKN300 32/25 Q1012 CB/NE/E/W
```

These come from https://beta.aviationweather.gov/, and from what I see, around 8% of their METARs fail to parse.

**Comment by lilopkins** [comment]
Looking into these, it appears that there are two issues:

- The US and Canada METARs aren't providing the full set of information that would usually be expected in a METAR. This can be resolved by assuming an inferred `///` where data is not supplied.
- The METAR from `MDSD` uses a non-standardised extra (`CB/NE/E/W`). For best compatibility, they should probably issue these after a `RMK` indicator, however it seems logical to allow this in the parser.

These will be fixed in the next update.

**Comment by lilopkins** [comment]
Version 0.7.7 should resolve this and these METARs have been added to the test suite.
